config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  resources :users

  resources :books do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!,except: [:top,:about]

    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
    user_path(resource)
    end




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    
  end

  def create
    @book =Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       @user = current_user
       render :index
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = User.find_by(id:@book.user_id)
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)

  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user

  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_errors.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>errors prohibited this obj from being saved:
  <% model.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/books/_new.html.erb
 <%= form_with model: book, local:true do |f| %>
    <div class="form-group">
      <%= f.label :Title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Opinion %>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success"  %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<div class="container mt-3">
   <div class="row">
     <div class="col-md-8 px-5 mx-auto">
<h1>Editing Book</h1>

<%= render 'books/errors',model: @book %>

 <%= form_with model:@book,local: true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class:"btn btn-secondary"  %>
  </div>
 <% end %>

  <%= link_to "Show", book_path(@book.id) %>
	|
  <%= link_to "Back", books_path %>

  </div>
  </div>
  </div>

app/views/books/index.html.erb
<div class="container px-5 mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/errors',model: @book %>
     <h2>User info</h2>
       <%= render 'users/info',user: @user %>

     <h2 class="">New book</h2>
       <%= render 'books/new',book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
     <table class='table table-hover table-inverse'>
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
               <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>

                    <%= link_to book_favorites_path(book), method: :delete do %>
                       ♥<%= book.favorites.count %> いいね
                    <% end %>
                 <% else %>

                    <%= link_to book_favorites_path(book), method: :post do %>
                       ♡<%= book.favorites.count %> いいね
                    <% end %>

                <% end %>
              </td>
            <td>コメント件数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
     </table>

    </div>

  </div>

</div>

app/views/books/show.html.erb
<div class="container px-5 mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/errors',model: @book %>
       <h2>User info</h2>
      <%= render 'users/info',user: @user %>
       <h2 class="mt-3">New book</h2>
      <%= render 'books/new',book: @new_book %>
    </div>

       <div class="col-md-8 offset-md-1">

         <h2>Book detail</h2>
  		     <table class='table'>
  		       <tr>
  		         <td>
  		           <%= link_to user_path(@book.user) do %>
  		             <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
  		             <%= @book.user.name %>
  		           <% end %>
  		         </td>
               <td><%= @book.title %></td>
               <td><%= @book.body %></td>

                  <td>
                     <% if @book.favorited_by?(current_user) %>

                         <%= link_to book_favorites_path(@book), method: :delete do %>
                            ♥<%= @book.favorites.count %> いいね
                         <% end %>

                      <% else %>

                         <%= link_to book_favorites_path(@book), method: :post do %>
                            ♡<%= @book.favorites.count %> いいね
                         <% end %>

                     <% end %>
                   </td>

               <td>コメント件数：<%= @book.book_comments.count %></td>

               <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, data:{confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" %></td>
               <% end %>
              </tr>
            </table>

            <table>
             <tbody>
              <tr>
                <% @book.book_comments.each do |book_comment| %>
                   <td>
                     <%= link_to user_path(book_comment.user) do %>
                       <%= attachment_image_tag book_comment.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "60x60" %><br>
                       <%= book_comment.user.name %>
                     <% end %>
                   </td>
                   <td><%= book_comment.comment %></td>

                  <td>
                   <% if book_comment.user == current_user %>

                        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete , class:"btn btn-sm btn-danger" %>

                   <% end %>
                  </td>
              </tr>
                <% end %>

             </tbody>
            </table>

            <div class="new-comment">
              <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
               <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class:"form-control" %>
               <%= f.submit "送信する" %>
              <% end %>
            </div>


    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container mt-3'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-3">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Replay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

     <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
     <li>
       <%= link_to user_path(current_user) do %>
        <i class="fas fa-home nav-link text-light"> Home</i>
       <% end %>
     </li>
     <li>
       <%= link_to users_path do %>
        <i class="fas fa-users nav-link text-light">Users</i>
       <% end %>
     </li>
     <li>
       <%= link_to books_path do %>
        <i class="fas fa-book-open nav-link text-light">Books</i>
       <% end %>
     </li>
     <li>
       <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt nav-link text-light">logout</i>
       <% end %>
     </li>
    <% else %>
     <li>
       <%= link_to "/" do %>
       　<i class="fas fa-home nav-link text-light">Home</i>
       <% end %>
     </li>
     <li>
       <%= link_to '/home/about' do  %>
        <i class="fas fa-link nav-link text-light">About</i>
       <% end %>
     </li>
     <li>
       <%= link_to new_user_registration_path do %>
        <i class="fas fa-user-plus nav-link text-light">sign up</i>
       <% end %>
     </li>
     <li>
       <%= link_to new_user_session_path do %>
        <i class="fas fa-sign-in-alt nav-link text-light">login</i>
       <% end %>
     </li>
    <% end %>
    </ul>
    </div>
    </div>
    </nav>
    </header>

     <% if flash[:notice] %>
     　<p id="notice">
       <%= flash[:notice] %>
    　 </p>
   　<% end %>

    <%= yield %>

    <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>

  </body>
</html>

app/views/users/_info.html.erb
<table class='table'>

  <tr><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

  <div class="row">
     <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
     <% end %>
  </div>

app/views/users/edit.html.erb
 <div class="container mt-3">
   <div class="row">
     <div class="col-md-8 px-5 mx-auto">
 <h2>User info</h2>

 <%= render 'books/errors',model: @user %>
    <%= form_with model:@user, local: true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class:"form-control name"%>
      </div>
     <div class="form-group">

        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class:"form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      </div>
    <% end %>

    </div>
    </div>
    </div>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">

<h2>User info</h2>
  <%= render 'users/info',user: @user %>

<h2 class="mt-3">New book</h2>
  <%= render 'books/new',book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">


<h2>Users</h2>
      <table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "60x60", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/errors',model: @user %>
      <h2>User info</h2>
        <%= render 'users/info',user: @user %>

      <h2 class="mt-3">New book</h2>
        <%= render 'books/new',book: @book %>
    </div>
     <div class="col-md-8 offset-md-1">


        <h2>Books</h2>
        <table class="table table-hover table-inverse">
           <thead>
             <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
             </tr>
           </thead>
          <tbody>
            <% @books.each do |book| %>
             <tr>
              <td>
               <%= link_to user_path(@user) do %>
                 <%= attachment_image_tag @user, :profile_image, size: '60x60', fallback: "no_image.jpg" %>
               <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
             </tr>
            <% end %>
          </tbody>
        </table>
     </div>
  </div>
</div>